-- please see database schema document for detailed specifications and some examples

BEGIN;

CREATE EXTENSION IF NOT EXISTS vector;


CREATE TABLE IF NOT EXISTS Schools (
	school_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	school_name TEXT CHECK(LENGTH(school_name) <= 75) UNIQUE NOT NULL,
	location_id INTEGER --foreign key constraint added later: location doesn't exist yet
);

CREATE TABLE IF NOT EXISTS Users (
	username TEXT PRIMARY KEY CHECK(LENGTH(username) >= 5 AND LENGTH(username)<=30),
	account_type TEXT CHECK(account_type IN ('admin', 'student')),
	hashed_password TEXT NOT NULL,
	created_timestamp TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Departments (
	department_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	school_id INTEGER REFERENCES Schools(school_id) ON DELETE CASCADE,
	department_name TEXT CHECK(LENGTH(department_name) <= 50),
	department_code TEXT CHECK(LENGTH(department_code) < 15),
	UNIQUE(school_id, department_name),
	UNIQUE(school_id, department_code)
);

CREATE TABLE IF NOT EXISTS Locations (
	location_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	open_hours JSONB,
	address_street TEXT CHECK(LENGTH(address_street)<50),
	address_room TEXT CHECK(LENGTH(address_room)<10),
	city TEXT CHECK(LENGTH(city)<=40),
	state_code CHAR(2) CHECK(state_code ~ '^[A-Z][A-Z]$'),
	zipcode VARCHAR(9) CHECK(zipcode ~ '^[0-9]{5}(-[0-9]{4})?$' ),
	location_notes TEXT CHECK(LENGTH(location_notes)<250),
	location_status TEXT CHECK(location_status IN ('active', 'closed permanently', 'closed temporarily')),
	on_campus BOOLEAN NOT NULL,
	school_id INTEGER REFERENCES Schools(school_id) ON DELETE SET NULL,
	department_id INTEGER REFERENCES Departments(department_id) ON DELETE SET NULL
);

ALTER TABLE Schools -- adding FK link
	ADD CONSTRAINT fk_school_location
	FOREIGN KEY(location_id) REFERENCES Locations(location_id) ON DELETE SET NULL;

CREATE TABLE IF NOT EXISTS Events (
	event_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	event_name TEXT NOT NULL CHECK(LENGTH(event_name)<= 75),
	event_time TSTZMULTIRANGE,
	time_recurring JSONB, -- for events that repeat based on weekdays
	CHECK(event_time IS NOT NULL OR time_recurring IS NOT NULL),
	event_location INTEGER REFERENCES Locations(location_id) ON DELETE SET NULL,
	event_description TEXT CHECK(LENGTH(event_description)<=200),
	event_creator TEXT REFERENCES Users(username) ON UPDATE CASCADE ON DELETE SET NULL,
	event_tags TEXT[],
	event_department INTEGER REFERENCES Departments(department_id) ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS Dining (
	dining_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	dining_name TEXT CHECK(LENGTH(dining_name)<= 75) NOT NULL,
	location_id INTEGER REFERENCES Locations(location_id) ON DELETE SET NULL,
	cuisine TEXT[],
	reservations BOOLEAN,
	event_status BOOLEAN
);

CREATE TABLE IF NOT EXISTS Courses (
	course_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	course_code VARCHAR(15) NOT NULL,
	department_id INTEGER NOT NULL REFERENCES Departments(department_id) ON DELETE CASCADE,
	course_number VARCHAR(10) NOT NULL,
	course_name TEXT CHECK(LENGTH(course_name)<=75) NOT NULL,
	course_description TEXT CHECK(LENGTH(course_description)<=500),
	course_credits REAL CHECK(course_credits>=0.00) NOT NULL
);


CREATE TABLE IF NOT EXISTS Sessions (
	session_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	school_id INTEGER NOT NULL REFERENCES Schools(school_id) ON DELETE CASCADE,
	session_name TEXT CHECK(LENGTH(session_name)<=50) NOT NULL,
	academic_year SMALLINT NOT NULL CHECK(academic_year >= 1960),
	session_start DATE NOT NULL,
	session_end DATE NOT NULL
);


CREATE TABLE IF NOT EXISTS Offerings (
	offering_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	course_crn VARCHAR(10),
	UNIQUE(offering_session, course_crn),
	course_id INTEGER NOT NULL REFERENCES Courses(course_id) ON DELETE CASCADE,
	location_id INTEGER REFERENCES Locations(location_id) ON DELETE SET NULL,
	class_timings JSONB,
	offering_session INTEGER NOT NULL REFERENCES Sessions(session_id) ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS Students (
	student_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	username TEXT NOT NULL REFERENCES Users(username) ON DELETE CASCADE ON UPDATE CASCADE,
	first_name TEXT CHECK(LENGTH(first_name)<=30) NOT NULL,
	last_names TEXT CHECK(LENGTH(last_names)<=50) NOT NULL,
	-- postgres doesn't allow dynamic functions like CURRENT_DATE in CHECK constraints
		--so dob below will need to be validated in the backend (at least 14yo)
	dob DATE NOT NULL CHECK(dob >= '1940-01-01'), 
	email TEXT NOT NULL CHECK(email ~ '^[A-Za-z0-9._%-]+@[A-Za-z0-9.-]+\.[A-Za-z0-9\-]{2,}$'),
	edu_email TEXT CHECK(edu_email ~ '^[A-Za-z0-9._%-]+@[A-Za-z0-9.-]+\.edu$'),
	zipcode VARCHAR(9) CHECK(zipcode ~ '^[0-9]{5}(-[0-9]{4})?$'),
	latitude_approx REAL,
	longitude_approx REAL,
	CHECK(zipcode IS NOT NULL OR (latitude_approx IS NOT NULL AND longitude_approx IS NOT NULL)),
	account_status TEXT NOT NULL CHECK(account_status IN ('pending', 'open', 'denied', 'closed')),
	created_at TIMESTAMPTZ,
	majors TEXT[],
	minors TEXT[],
	interests TEXT[],
	dislikes TEXT[], 
	account_denied INTEGER DEFAULT 0 CHECK(account_denied>=0)
);


CREATE TABLE IF NOT EXISTS Deadlines (
	deadline_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	student_id INTEGER REFERENCES Students(student_id) ON DELETE CASCADE,
	deadline_action TEXT NOT NULL, 
	deadline_datetime TIMESTAMPTZ NOT NULL,
	deadline_description TEXT
);


CREATE TABLE IF NOT EXISTS Instructors (
	instructor_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	instructor_fname TEXT NOT NULL CHECK(LENGTH(instructor_fname)<30),
	instructor_lnames TEXT NOT NULL CHECK(LENGTH(instructor_lnames)<50),
	instructor_department INTEGER NOT NULL REFERENCES Departments(department_id) ON DELETE CASCADE,
	instructor_email TEXT NOT NULL CHECK(instructor_email ~ '^[A-Za-z0-9._%-]+@[A-Za-z0-9.-]+\.edu$'),
	instructor_office INTEGER REFERENCES Locations(location_id) ON DELETE SET NULL,
	instructor_hours JSONB
);


CREATE TABLE IF NOT EXISTS Reviews_generic (
	review_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	student_id INTEGER NOT NULL REFERENCES Students(student_id)  ON DELETE CASCADE,
	school_id INTEGER NOT NULL REFERENCES Schools(school_id) ON DELETE CASCADE,
	rating NUMERIC NOT NULL CHECK(rating % 0.5 = 0 AND rating >= 1 AND rating <= 5),
	review_tags TEXT[],
	review_title TEXT NOT NULL CHECK(LENGTH(review_title) <= 30),
	review_comment TEXT NOT NULL CHECK(LENGTH(review_comment)<=500),
	upvote_count INTEGER DEFAULT 0 CHECK(upvote_count >= 0),
	downvote_count INTEGER DEFAULT 0 CHECK(downvote_count >= 0),
	anonymous BOOLEAN NOT NULL DEFAULT FALSE,
	anonymous_username TEXT CHECK(LENGTH(anonymous_username) <= 35 AND anonymous_username ~ '^[A-Za-z]+_[A-Za-z]+[0-9]{2}$'),
	submitted TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	attachments TEXT[] CHECK(CARDINALITY(attachments)<=5)
);


CREATE TABLE IF NOT EXISTS Review_votes (
	review_id INTEGER NOT NULL REFERENCES Reviews_generic(review_id) ON DELETE CASCADE,
	voter_id INTEGER NOT NULL REFERENCES Students(student_id) ON DELETE CASCADE,
	is_upvote BOOLEAN NOT NULL,
	vote_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (voter_id,review_id)
);

--automatically update vote count when vote is inserted/removed
CREATE OR REPLACE FUNCTION update_review_votes()
RETURNS TRIGGER AS $$
BEGIN
    UPDATE Reviews_generic
    SET 
        upvote_count = (SELECT COUNT(*) FROM Review_votes WHERE review_id = COALESCE(NEW.review_id, OLD.review_id) AND is_upvote = TRUE),
        downvote_count = (SELECT COUNT(*) FROM Review_votes WHERE review_id = COALESCE(NEW.review_id, OLD.review_id) AND is_upvote = FALSE)
    WHERE review_id = COALESCE(NEW.review_id, OLD.review_id);
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_update_review_votes AFTER INSERT OR UPDATE OR DELETE ON Review_votes
FOR EACH ROW EXECUTE FUNCTION update_review_votes();



CREATE TABLE IF NOT EXISTS Review_replies (
	reply_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	review_id INTEGER NOT NULL REFERENCES Reviews_generic(review_id) ON DELETE CASCADE,
	parent_id INTEGER REFERENCES Review_replies(reply_id) ON DELETE CASCADE,
	replier_id INTEGER NOT NULL REFERENCES Students(student_id) ON DELETE CASCADE,
	anonymous_reply BOOLEAN NOT NULL DEFAULT FALSE,
	anonymous_username TEXT CHECK(LENGTH(anonymous_username) <= 35 AND anonymous_username ~ '^[A-Za-z]+_[A-Za-z]+[0-9]{2}$'),
	reply_content TEXT NOT NULL CHECK(LENGTH(reply_content)<=250),
	reply_attachments TEXT[] CHECK(CARDINALITY(reply_attachments)<=2),
	reply_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);



CREATE TABLE IF NOT EXISTS Reviews_educational (
	review_id INTEGER PRIMARY KEY REFERENCES Reviews_generic(review_id) ON DELETE CASCADE,
	student_id INTEGER REFERENCES Students(student_id) ON DELETE CASCADE,
	offering_id INTEGER REFERENCES Offerings(offering_id) ON DELETE CASCADE,
	instructor_id INTEGER REFERENCES Instructors(instructor_id) ON DELETE CASCADE,
	department_id INTEGER REFERENCES Departments(department_id) ON DELETE CASCADE,
	CHECK(offering_id IS NOT NULL OR instructor_id IS NOT NULL OR department_id IS NOT NULL),
	UNIQUE(student_id, offering_id, instructor_id,department_id), -- shouldn't interfere with reviews for individual things since NULL <> NULL
	class_method TEXT CHECK(class_method IN ('in-person', 'hybrid', 'online', 'online with in-person exams')),
	student_tips TEXT CHECK(LENGTH(student_tips)<=100)
);


CREATE TABLE IF NOT EXISTS Reviews_dining (
	review_id INTEGER PRIMARY KEY REFERENCES Reviews_generic(review_id) ON DELETE CASCADE,
	dining_id INTEGER NOT NULL REFERENCES Dining(dining_id) ON DELETE CASCADE,
	ordered_items TEXT[] NOT NULL CHECK(CARDINALITY(ordered_items)>0),
	diner_count INTEGER DEFAULT 1 CHECK(diner_count>=0),
	spent_range INT4RANGE NOT NULL,
	order_method TEXT NOT NULL CHECK(order_method IN ('dine-in','drive-through', 'pickup', 'delivery', 'other app delivery')),
	cleanliness_rating NUMERIC CHECK(cleanliness_rating % 0.5 = 0 AND cleanliness_rating >= 1 AND cleanliness_rating <= 5),
	service_rating NUMERIC CHECK(service_rating % 0.5 = 0 AND service_rating >= 1 AND service_rating <= 5),
	spiciness_rating NUMERIC CHECK(spiciness_rating % 0.5 = 0 AND spiciness_rating >= 1 AND spiciness_rating <= 5),
	recommended_food TEXT[],
	avoid_food TEXT[],
	accommodates_diets TEXT[] CHECK(accommodates_diets <@ 
		ARRAY['halal', 'vegan', 'vegetarian', 'hindu', 'pescetarian','kosher', 'lactose-intolerant', 'gluten-free']),
	drive_through BOOLEAN,
	quick_service BOOLEAN,
	recommend_couples BOOLEAN,
	recommend_groups BOOLEAN
);


CREATE TABLE IF NOT EXISTS Dining_items (
	item_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	dining_id INTEGER NOT NULL REFERENCES Dining(dining_id) ON DELETE CASCADE,
	item_name TEXT NOT NULL CHECK(LENGTH(item_name) < 100),
	item_price REAL NOT NULL CHECK(item_price>0.00),
	item_calories INTEGER CHECK(item_calories>0 AND item_calories<=8000),
	item_ingredients TEXT[],
	dietary_tags TEXT[] CHECK(dietary_tags <@ 
		ARRAY['halal', 'vegan', 'vegetarian', 'hindu', 'pescetarian','kosher', 'lactose-intolerant', 'gluten-free']),
	entered_by TEXT REFERENCES Users(username) ON UPDATE CASCADE  ON DELETE CASCADE
);



CREATE TABLE IF NOT EXISTS Reviews_resources (
	review_id INTEGER PRIMARY KEY REFERENCES Reviews_generic(review_id)  ON DELETE CASCADE,
	resource_type TEXT NOT NULL CHECK(resource_type IN 
		('academic', 'campus facilities', 'tech support', 'parking', 'internet/WiFi', 'management', 'club/org', 'fundraising')),
	campus_staff TEXT[]
);


CREATE TABLE IF NOT EXISTS Authentications (
	authentication_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	student_id INTEGER NOT NULL REFERENCES Students(student_id) ON DELETE CASCADE,
	status TEXT NOT NULL CHECK(status IN ('pending', 'approved', 'denied')),
	documents TEXT[] CHECK(CARDINALITY(documents)<=5),
	admin_message TEXT CHECK(LENGTH(admin_message)<=250),
	submitted_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	reviewed_time TIMESTAMPTZ CHECK(reviewed_time >= submitted_time), -- = for auto-approval
	last_resend TIMESTAMPTZ,
	resend_count INTEGER DEFAULT 0 CHECK(resend_count>=0)
);

--auto-delete student authentication documents after review is finished + increment denied counter if needed
CREATE OR REPLACE FUNCTION delete_auth_documents()
RETURNS TRIGGER AS $$
BEGIN
    NEW.documents := NULL;
    IF NEW.status = 'denied' THEN
		UPDATE Students 
        SET account_denied = account_denied+1 
        WHERE student_id = NEW.student_id;
    END IF;
	
	RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_delete_auth_docs
BEFORE UPDATE ON Authentications
FOR EACH ROW
	WHEN (NEW.status IN ('approved', 'denied') AND OLD.status = 'pending')
	EXECUTE FUNCTION delete_auth_documents();




CREATE TABLE IF NOT EXISTS Notifications (
	notification_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	username TEXT NOT NULL REFERENCES Users(username) ON DELETE CASCADE ON UPDATE CASCADE,
	notification_title TEXT NOT NULL CHECK(LENGTH(notification_title)<=50),
	notification_message TEXT CHECK(LENGTH(notification_message)<=500),
	sent_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	read_time TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS Groups (
	group_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	group_name TEXT NOT NULL CHECK(LENGTH(group_name)<=75),
	group_description TEXT,
	group_owner TEXT REFERENCES Users(username) ON UPDATE CASCADE ON DELETE SET NULL,
	is_verified BOOLEAN DEFAULT FALSE,
	created_at DATE DEFAULT CURRENT_DATE,
	school_id INTEGER REFERENCES Schools(school_id) ON DELETE SET NULL,
	department_id INTEGER REFERENCES Departments(department_id) ON DELETE SET NULL,
	group_type TEXT NOT NULL CHECK(group_type IN ('class','club', 'year', 'major', 'college', 'other')),
	group_contact JSONB,
	group_links JSONB
);


CREATE TABLE IF NOT EXISTS Memberships (
	username TEXT NOT NULL REFERENCES Users(username) ON DELETE CASCADE ON UPDATE CASCADE,
	group_id INTEGER NOT NULL REFERENCES Groups(group_id) ON DELETE CASCADE,
	PRIMARY KEY(username, group_id),
	roles TEXT[],
	membership_start TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	membership_end TIMESTAMPTZ,
	membership_status TEXT NOT NULL CHECK(membership_status IN ('active', 'pending', 'denied', 'cancelled')),
	documents TEXT[]
);


CREATE TABLE IF NOT EXISTS Registrations (
	student_id INTEGER REFERENCES Students(student_id) ON DELETE CASCADE,
	offering_id INTEGER REFERENCES Offerings(offering_id) ON DELETE CASCADE,
	study_group BOOLEAN DEFAULT FALSE,
	auditing BOOLEAN DEFAULT FALSE,
	PRIMARY KEY(student_id, offering_id)
);


CREATE TABLE IF NOT EXISTS Event_responses (
	response_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	username TEXT NOT NULL REFERENCES Users(username) ON DELETE CASCADE ON UPDATE CASCADE,
	event_id INTEGER NOT NULL REFERENCES Events(event_id) ON DELETE CASCADE,
	response_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	user_action TEXT NOT NULL CHECK(user_action IN ('saved', 'dismissed', 'opened'))
);


CREATE TABLE IF NOT EXISTS Scraped_information (
	chunk_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	source_urls TEXT[] NOT NULL,
	content TEXT NOT NULL,
	embedding VECTOR(1536)
);


CREATE TABLE IF NOT EXISTS Attendance (
	student_id INTEGER REFERENCES Students(student_id) ON DELETE CASCADE,
	offering_id INTEGER REFERENCES Offerings(offering_id) ON DELETE CASCADE,
	attendance_date DATE,
	student_present BOOLEAN NOT NULL,
	PRIMARY KEY(student_id, offering_id, attendance_date)
);


--FK indexes
CREATE INDEX IF NOT EXISTS idx_offerings_course ON Offerings(course_id);
CREATE INDEX IF NOT EXISTS idx_offerings_session ON Offerings(offering_session);
CREATE INDEX IF NOT EXISTS idx_reviews_student ON Reviews_generic(student_id);
CREATE INDEX IF NOT EXISTS idx_reviews_school ON Reviews_generic(school_id);
CREATE INDEX IF NOT EXISTS idx_review_replies_review ON Review_replies(review_id);
CREATE INDEX IF NOT EXISTS idx_review_votes_review ON Review_votes(review_id);
CREATE INDEX IF NOT EXISTS idx_registrations_student ON Registrations(student_id);


COMMIT;